### PR TITLE
Test dockstore imports into terra.

### PR DESCRIPTION
**Pull request by DailyDreaming**
Built on top of https://github.com/DataBiosphere/bdcat-integration-tests/pull/5.  Diff should be reduced when that's merged.

### CODE REVIEW

File: test/utils.py [hunk 1]
```diff
@@ -95,4 +96,140 @@ def fetch_google_secret(secret):
...
+        "namespace": billing_project,
+        "name": "UM_aligner_wdl",
+        "rootEntityType": "",
+        "inputs": {},
+        "outputs": {},
+        "prerequisites": {},
+        "methodRepoMethod":  {
+            "sourceRepo": "dockstore",
+            "methodPath": "github.com/DataBiosphere/topmed-workflows/UM_aligner_wdl",
+            "methodVersion": "1.32.0"
```
[the remark this answers is not in the document]
Comment (DailyDreaming) [reply test/utils.py:163]: That's a good point.  I think it would be a better integration test if we exercise dockstore's workflow creation api before importing as well.

File: test/utils.py [hunk 2]
```diff
@@ -95,4 +96,140 @@ def fetch_google_secret(secret):
...
     response = client.access_secret_version(f'projects/{GOOGLE_PROJECT_NAME}/secrets/{secret}/versions/latest')
-    return response.payload.data.decode('UTF-8')
+    return response.payload.data.decode('utf-8')
+
+
+def mint_access_token():
+    p = subprocess.Popen('gcloud auth application-default print-access-token',
+                         shell=True,
+                         stdout=subprocess.PIPE, stderr=subprocess.PIPE)
+    stdout, stderr = p.communicate()
```
[the remark this answers is not in the document]
Comment (DailyDreaming) [reply test/utils.py:106]: This breaks on python3.6 (but works on python3.7+):

```
>>> foo = subprocess.run(['ls'], shell=True, capture_output=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

I originally used run, but have had to tweak it in so many situations, that I just default to `subprocess.Popen` now.  I feel it's more powerful and seems to be compatible across all python versions.

File: test/utils.py [hunk 3]
```diff
@@ -95,4 +96,140 @@ def fetch_google_secret(secret):
...
     client = SecretManagerServiceClient()
     response = client.access_secret_version(f'projects/{GOOGLE_PROJECT_NAME}/secrets/{secret}/versions/latest')
-    return response.payload.data.decode('UTF-8')
+    return response.payload.data.decode('utf-8')
+
+
+def mint_access_token():
+    p = subprocess.Popen('gcloud auth application-default print-access-token',
+                         shell=True,
+                         stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```
[the remark this answers is not in the document]
Comment (DailyDreaming) [reply test/utils.py:105]: Good idea!  Just ran it and it worked like a charm.

File: test/test_basic_submission.py [hunk 4]
```diff
@@ -51,6 +58,72 @@ def tearDownClass(cls) -> None:
...
             os.remove(cls.drs_file_path)
 
+    def test_dockstore_import_in_terra(self):
+        """"""
+        # import the workflow into terra
+        response = import_dockstore_wf_into_terra()
+        method_info = response['methodConfiguration']['methodRepoMethod']
+        assert method_info['sourceRepo'] == 'dockstore'
+        assert method_info['methodPath'] == 'github.com/DataBiosphere/topmed-workflows/UM_aligner_wdl'
+        assert method_info['methodVersion'] == '1.32.0'
```
[the remark this answers is not in the document]
Comment (DailyDreaming) [reply test/test_basic_submission.py:68]: No real reason, I suppose the culprit is that I don't have strong feelings about either.  Is there an advantage to the unittest methods over a simple assert?

File: test/utils.py (hunk 1 above)
[the remark this answers is not in the document]
Comment (DailyDreaming) [reply test/utils.py:152]: I've created an issue: #11

File: test/test_basic_submission.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (xbrianh) [reply test/test_basic_submission.py]: The unittest methods often contain more functionality than simple assertions, e.g. [assertSequenceEqual](https://github.com/python/cpython/blob/d9c1f1991969e99791de75b2bc935e6445bc5dcd/Lib/unittest/case.py#L922-L1019). They also contain unttest API functionality such as message formatting and exception failure configuration... but this is something you would need to look into yourself.
